### ISSUE TITLE
If you use KDE there can be problems with opening the browser automatically

### ISSUE THREAD

**Issue by inmysocks** [OokTech/TW5-BobEXE#13]
See: https://groups.google.com/forum/#!topic/tiddlywiki/sXgJsW8DaJw

**Comment by caph1993** [comment]
I am getting a similar but different error in my (non-kde) linux mint. I guess the issue is related to google-chrome, but there's no way I can tell BobEXE not to launch chrome by default.

```
➜  ./BobLinux

NodeSettings - Parsed raw settings.
TiddlyWiki version 5.1.19 with Bob version 1.2.2r2
Serving on 127.0.0.1:8080
(press ctrl-C to exit)
/snapshot/BobEXE/node_modules/openurl/openurl.js:39
                throw error;
                ^

Error: [10308:10308:0422/235621.100197:ERROR:sandbox_linux.cc(364)] InitializeSandbox() called with multiple threads in process gpu-process.
[10271:10291:0422/235621.166779:ERROR:browser_process_sub_thread.cc(209)] Waited 10 ms for network service

    at Socket.<anonymous> (/snapshot/BobEXE/node_modules/openurl/openurl.js:35:25)
    at Socket.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1081:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by inmysocks** [comment]
To disable having the browser open automatically you can set the suppressBrowser key to true in settings.json as described in the configuration documentation here https://github.com/OokTech/TW5-Bob/blob/master/Documentation/Configuration.tid

The first time you start the executable it will create the index wiki folder with a settings folder inside it. That is where you find the settings.json file.

**Comment by caph1993** [comment]
Thanks. Setting `suppressBrowser` to `true` as you suggested solved my issue. And I can access with google chrome without any problem.
