### ISSUE TITLE
Version 1.6.2r2 not working on Linux

### ISSUE THREAD

**Issue by tejasvi** [OokTech/TW5-BobEXE#20]
Steps to reproduce:
1. Obtain https://github.com/OokTech/TW5-BobEXE/releases/download/1.6.2r2/BobLinux
2. `chmod +x BobLinux`
3. `./BobLinux` gives,
```Error executing boot module $:/plugins/OokTech/Bob/FileSystemMonitor.js: {}

$:/plugins/OokTech/Bob/FileSystemMonitor.js:24
if($tw.node && $tw.settings.disableFileWatchers !== 'yes') {
                            ^

TypeError: Cannot read property 'disableFileWatchers' of undefined
    at $:/plugins/OokTech/Bob/FileSystemMonitor.js:24:29
    at $:/plugins/OokTech/Bob/FileSystemMonitor.js:229:3
    at Script.runInContext (vm.js:127:20)
    at Script.runInNewContext (vm.js:133:17)
    at Object.runInNewContext (vm.js:299:38)
    at Object.$tw.utils.evalSandboxed (/root/Bob/TiddlyWiki5/boot/boot.js:530:5)
    at Object.$tw.modules.execute (/root/Bob/TiddlyWiki5/boot/boot.js:806:15)
    at /root/Bob/TiddlyWiki5/boot/boot.js:846:30
    at Object.$tw.utils.each (/root/Bob/TiddlyWiki5/boot/boot.js:135:12)
    at Object.$tw.modules.forEachModuleOfType (/root/Bob/TiddlyWiki5/boot/boot.js:845:12)
```
Version 1.6.0b1 works, but since I use Git for syncing, 1.6.2r2 prevents the silent tiddler deletion. Plugin version works fine.

**Comment by tejasvi** [comment]
I did some digging and found the issue with the Bob plugin instead. Opened https://github.com/OokTech/TW5-Bob/issues/162
