### ISSUE TITLE
I can't update from the previous versio

### ISSUE THREAD

**Issue by ghost** [OokTech/TW5-BobEXE#21]
Hi, I wanted to update bob version and replaced executable in my wiki to bob 1.7.1 Linux version, but the operation ended with disaster:

```
NodeSettings - Parsed raw settings.
Added route /^\/knowledge-management\/?$/
Added route /^\/knowledge-management\/tech-wiki\/?$/
Added route /^\/knowledge-management\/mysterious-wiki\/?$/
Added route /^\/knowledge-management\/scientific-wiki\/?$/
Added route /^\/knowledge-management\/psyche-wiki\/?$/
Added route /^\/documentations\/?$/
Added route /^\/documentations\/private-computing-system\/?$/
Added route /^\/projects\/?$/
Added route /^\/projects\/hobby-wiki\/?$/
Added route /^\/resources\/?$/
Added route /^\/resources\/resources-wiki\/?$/
Added route /^\/resources\/z_template\/?$/
Added route /^\/personal\/?$/
Added route /^\/personal\/personal-wiki\/?$/
TiddlyWiki version 5.1.23 with Bob version 1.7.1
Bob saver server running on 127.0.0.1:61192
Serving on 127.0.0.1:8080
(press ctrl-C to exit)
new connection
No Themes Folder /home/slawek/mnt/decrypted/personal.mnt/notatki/personal-wiki/Themes
No Plugins Folder /home/slawek/mnt/decrypted/personal.mnt/notatki/personal-wiki/Plugins
fs.js:127
    throw err;
    ^

Error: ENOENT: no such file or directory, scandir '/home/slawek/mnt/decrypted/personal.mnt/notatki/personal-wiki/Editions'
    at Object.readdirSync (fs.js:837:3)
    at Object.readdirSync (/home/slawek/mnt/decrypted/personal.mnt/personal-wiki/BobLinux:153:50)
    at Object.exports.getEditionInfo ($:/core/modules/utils/edition-info.js:28:21)
    at Object.ServerSide.getViewableLanguagesList ($:/plugins/OokTech/Bob/ServerSide.js:781:35)
    at Object.exports.handler ($:/plugins/OokTech/Bob/ServerRoutes/get-status.js:35:41)
    at SimpleServer.requestHandler ($:/plugins/OokTech/Bob/commands/wsserver.js:262:15)
    at Server.emit (events.js:209:13)
    at parserOnIncoming (_http_server.js:733:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:115:17) {
  errno: -2,
  syscall: 'scandir',
  code: 'ENOENT',
  path: '/home/slawek/mnt/decrypted/personal.mnt/notatki/personal-wiki/Editions'
}
```
Could you please advise?

**Comment by inmysocks** [comment]
There is something about how the core checks editions that doesn't play well with BobEXE. Somehow the core thinks that there is an editions folder and tries to read it without checking to see if it exists first. 
I think that it is caused by how nexe handles the file system packaged in the executable.

As a work around, if you manually create the folder Editions at the path given in the error it should let you use everything normally.

**Comment by ghost** [comment]
That did the trick, now I have newest version, thanks!

**Comment by ghost** [comment]
Issue was resolved, please close issue
